### ISSUE TITLE
`get_process` does not find dataframes with multiple subjects.

### ISSUE THREAD

**Issue by FelixMau** [sedos-project/data_adapter#10]
When trying to get a DataFrame for a process that has multiple subject entries None gets returned. 

This issue should be fixed by additionally improving the passed processes by each FW data_adapter. 
However, this may result in naming conflicts, as all relevant `Subject/isAbout` fields related to the process should have uniform naming and may lead to complications if a single `Subject/isAbout` entry is utilized by multiple processes.
`Subject`/`isAbout` entries are joined by `_`.

**Comment by henhuy** [comment]
Do you have an example?
On my side it's working with following example:
```
def test_multiple_subject_entries():
    metadata = {
        "name": "meta_name",
        "subject": [{"name": "test"}, {"name": "test2"}]
    }
    assert ontology.get_subject(metadata) == "test_test2"
```

**Comment by henhuy** [comment]
Discussed bilateral.
Outcome: A process (i.e. ["wind_turbine"]) is not combined with another process holding two subjects (i.e. ["wind_turbine", "onshore"]). This cannot be done in data_adapter as this could lead to unwanted combinations IMO.
Current solution to add parameters from second process to first one, is to add those parameters via link (in link CSV):
```
process;table_name;column_name
wind_turbine;wind_turbine_onshore;param1
wind_turbine;wind_turbine_onshore;param2
...
```
