### ISSUE TITLE
Is ES structure example mature?

### ISSUE THREAD

**Issue by chrwm** [sedos-project/data_adapter#11]
I was wondering if the input & output information in [HARDCODED_ES_STRUCTURE](https://github.com/sedos-project/data_adapter/blob/dev/structures/HARDCODED_ES_STRUCT.json) are all necessary for modelling the process in a ESM framework/model - and if the example is mature?

E.g. in case of processes with only one input and one output, such as `battery storage`. Is it necessary to specify `electricity` for all given parameters or would specifying it as input&output for `input_ratio` be enough?

I'm asking, because from the example it is not clear to me which parameters per process need to be collected with inputs&outputs in the `process-parameter-input-ouput` [table ](https://github.com/sedos-project/data_adapter/blob/feature-2-collect-energy-vectors/tests/test_data/test_mimo/user_mimos.csv)by the APs to provide sufficient information for modelling.

I wouldn't have expected `installed capacity` in there, especially not for processes with only one input & output.

**Comment by chrwm** [comment]
In my opinion parameters should only be associated with inputs & outputs if they an influence them.

**Comment by henhuy** [comment]
That is also my understanding. But we must ensure that structure is working for the other FWs as well. Maybe some mimos could be removed - not sure about it

**Comment by anik-ier** [comment]
FOR TIMES, as far as I understand- simple 'process-parameter-input-ouput' table (which unfortunately not available now) that @chrwm suggested should be enough.

**Comment by FelixMau** [comment]
Please find an updated version of the structure in: c5267e0349f7d9cc3ebfe8fe409d3986aee0ba05
As we discussed before I did not make changes to the process parameters at this stage.
Also there are two structure versions.
First "hack-a-thon _by_subject" shall be used. After upcoming update "hack-a-thon_by_file_name" can be used to when processes are matched by file name.
To also get the onshore wind timeseries the collection.json, metadata for onshore wind and structure file have to be adjusted or wait for[ `additional_parameter`](https://github.com/sedos-project/data_adapter/blob/c5267e0349f7d9cc3ebfe8fe409d3986aee0ba05/data_adapter/structure.py#L20#L26) function to be refined

**Comment by chrwm** [comment]
We discussed the introduction of a `default` parameter.
The `default` parameter can be used to define the input-output relation of a process and its parameters - unless otherwise specified.

**1:1**
|process | parameter | input | output |
| -| -|- |- |
|wind_turb|default | wind | electricity|

wind_turb.csv
id | region | year | efficiency | lifetime | installed_cap | hub_height | bandwidth_type | version | method | source | comment
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --


extend with n:1, 1:n, n:n example

**Comment by henhuy** [comment]
Can we close then?

**Comment by chrwm** [comment]
Sure.
