### ISSUE TITLE
HARDCODED_ES_STRUCT.json when installing data_adapter via pip

### ISSUE THREAD

**Issue by JohannesBehrens** [sedos-project/data_adapter#12]
When installing the data_adapter via pip (pip install git+https://github.com/sedos-project/data_adapter.git@dev) only the .py files are installed and the HARDCODED_ES_STRUCT.json file is missing. Therefore the following erro ocuurs when importing the structure modul of the data_adapter:
![grafik](https://user-images.githubusercontent.com/120372257/218744400-2c1a8e21-25a9-41c1-97e5-5ce54701ea65.png)

Do I need to install the package in a certain way to solve this problem?

**Comment by FelixMau** [comment]
I think this issue belongs to the download_collection functionality as well. As the install does not create the collection folder within the `site-package` folder the download fails. 

As a **fix** you can set os.environ["COLLECTION_DIR"] to the path where you downloaded / want to download your collection and set os.environ["STRUCTURES_DIR"] to the path where you have downloaded the HARDCODED_ES_STRUCT.json
I.E. 
`import os'`
`os.environ["COLLECTION_DIR"] = "/home/local/.../data_adapter_oemof/tests/collections"`
`os.environ["STRUCTURES_DIR"] = "/home/local/.../data_adapter_oemof/tests/collections/hack-a-thon"`

**Comment by FelixMau** [comment]
As a `fix` you can set os.environ["COLLECTION_DIR"] to the path where you downloaded / want to download your collection and set os.environ["STRUCTURES_DIR"] to the path where you have downloaded the HARDCODED_ES_STRUCT.json

**Comment by henhuy** [comment]
Normally structures are not stored within the repo (I thought this would work for the hardcoded json).
Easiest way to solve this, would be to use current dev (where I changed default structures folder to `current-woking-dir/structures` and to copy content from [Hardcoded ES](https://github.com/sedos-project/data_adapter/blob/dev/structures/HARDCODED_ES_STRUCT.json) into this folder as HARDCOEDED_ES_STRUCT.json. then it should work.

**Comment by henhuy** [comment]
With latest update structures are read in from CSV.
By default, structure folder "structures" in current working directory is used.
There is an existing structure in https://github.com/sedos-project/data_adapter/blob/dev/tests/test_data/test_structures/modex_example.csv which can be copied into structures folder to have a working example.
