### ISSUE TITLE
Process names inconsistent

### ISSUE THREAD

**Issue by henhuy** [sedos-project/data_adapter#13]
@JohannesBehrens you mentioned that process names are inconsistent.
But I could not find where?
Could you give me a hint/example where to look at? Thanks!

**Comment by JohannesBehrens** [comment]
for the process names returned by the strucutre.get_processes or structure.get_energy_structure function the preprocessing.get_process function is not able to return data and instead only retrurns empty dataframes:
![grafik](https://user-images.githubusercontent.com/120372257/224681953-2b34c0ad-e4f3-4d1a-83a3-d82996654c68.png)

**Comment by henhuy** [comment]
You are using an outdated structure csv.
Could you please retry with structure "hack-a-thon_by_file_name"?

**Comment by JohannesBehrens** [comment]
This leads me to the following error:
![grafik](https://user-images.githubusercontent.com/120372257/224697272-5c74c538-e1fb-4e1e-bce8-6bd0ddddbf65.png)

Maybe my Collection Version (v2) is the problem... But unfortunately I cannot update my collection at the moment, as I cannot reach the databus

**Comment by henhuy** [comment]
Your command works on my machine...
I just tried to reach databus. For me databus is reachable and following code works:
```
from data_adapter import databus
databus.download_collection("https://energy.databus.dbpedia.org/felixmaur/collections/hack-a-thon/")
```

**Comment by JohannesBehrens** [comment]
Ok now it works for me as well and the databus is reachable again. Problem was that I had USE_ANNOTATIONS on True.
