### ISSUE TITLE
Get process does not return links anymore

### ISSUE THREAD

**Issue by FelixMau** [sedos-project/data_adapter#16]
https://github.com/sedos-project/data_adapter/blob/9dcac10cfb605852bc22951bd3ce1626545addff/data_adapter/preprocessing.py#L302-L303

Adapter is called with two possitional arguments in wrong order and thus misstakes the passed links as `structure_name`:

https://github.com/sedos-project/data_adapter/blob/9dcac10cfb605852bc22951bd3ce1626545addff/data_adapter/preprocessing.py#L33-L34

**Comment by henhuy** [comment]
Should be fixed in updated version v0.9.1
