### ISSUE TITLE
Enchancement: Flexible Merge groups

### ISSUE THREAD

**Issue by FelixMau** [sedos-project/data_adapter#17]
https://github.com/sedos-project/data_adapter/blob/9dcac10cfb605852bc22951bd3ce1626545addff/data_adapter/preprocessing.py#L14-L20

Data can not be processed if the dataset does not contain the default MERGE_GROUPS. 
Maybe we could add a check, whether the required MERGE_GROUP data is included in the Dataset and and/or reduce the grouping according to the passed Data.
For example if no year (for scalars) is passed merging would only take place by regions and we could give a warning?

Should we include minimal required input data in [docs](https://github.com/sedos-project/organization/blob/develop/docs/data_requirements/input_data.md)?

**Comment by henhuy** [comment]
For simplicity reasons, I would rather raise an error if one of those columns is not present in data table..
