### ISSUE TITLE
Enhancement: Get Regions

### ISSUE THREAD

**Issue by FelixMau** [sedos-project/data_adapter#18]
Request to implement a function that allows me to get all regions mentioned in the Data. This function would be helpful to know all occurring (possible) busses within the energy system.

**Comment by henhuy** [comment]
I think current implementation of process knows related regions - maybe this is enough with latest bus mapping implementation?

**Comment by FelixMau** [comment]
Yes representation within the processes is actually sufficient and it is possible to implement this way. 
The reason for this issue is for creating the bus.csv where I would need to include all the busses occurring. Because I need to create a bus for each commodity within each region.

**Comment by henhuy** [comment]
Maybe you could store each occurring bus while iterating through processes?
