### ISSUE TITLE
Add script to get mimo parameters

### ISSUE THREAD

**Issue by chrwm** [sedos-project/data_adapter#2]
Add script to get inputs and outputs for processes from csv for sql database

**Comment by henhuy** [comment]
@FelixMau this is the issue with related PR to overcome hardcoded ES, and instead read structure from CSV.
If you have time, could you start to rewrite Hardcoded ES into `modex.csv` in folder `structures`?
Then I would add section in README on how to activate structure.

**Comment by henhuy** [comment]
done
