### ISSUE TITLE
Timeseries refactoring refactors each year in seperate collumn

### ISSUE THREAD

**Issue by FelixMau** [sedos-project/data_adapter#24]
When refactoring from "parameter model" to pandas dataframe with timeseriesindex a seperate collumns is created for each year (example from `hack-a-thon` data):
![grafik](https://github.com/sedos-project/data_adapter/assets/98911066/982a20c3-5a91-43db-bfaa-85ec52166234)

Also it would be interesting to me if we will keep the Multiindex Dataframe or instead use `name_region` (or similar) for multiple `timeseries`. I think both would be nice but I am not sure if this is a fixed decision?

**Comment by henhuy** [comment]
I think, I silently fixed this already.
See https://github.com/sedos-project/data_adapter/blob/2e81c2a145123023e1a863bf835255611775f0af/CHANGELOG.md#L22

Can you confirm?

**Comment by FelixMau** [comment]
Sorry, Ive been working on the wrong version and did not see changes thank you for pointing out!

Unfortunately I still get the bug, when requesting `adapter.get_process('modex_tech_wind_turbine_onshore').timeseries` from hack-a-thon Adapter. 

![image](https://github.com/sedos-project/data_adapter/assets/98911066/5627f69b-eaef-4dfe-8f89-77cee03c80a6)

**Comment by henhuy** [comment]
Okay - I will have a look.
One question: Which one is the hack-a-thon dataset at databus https://databus.openenergyplatform.org/felixmaur ?

**Comment by FelixMau** [comment]
You can find it [here](https://databus.openenergyplatform.org/felixmaur/collections/hack-a-thon) in `collections`

**Comment by henhuy** [comment]
thx

**Comment by FelixMau** [comment]
I've been working on the wrong environment, sorry for trouble caused.
