### ISSUE TITLE
`download_collection` fails

### ISSUE THREAD

**Issue by jnnr** [sedos-project/data_adapter#9]
This test began to fail recently:

https://github.com/sedos-project/data_adapter_oemof/blob/feature/build-minimal-example/tests/test_databus_connection.py

```
No such file or directory: '/data_adapter_oemof/../collections/modex_test_renewable'
```

**Comment by FelixMau** [comment]
Should be resolved by: https://github.com/sedos-project/data_adapter/pull/8

**Comment by henhuy** [comment]
Collections directory can either be set by environment variable (will add it to  docs) or is set as default path (currently points to "collections" folder in data_adapter - will change it to CWD).
Will use PR from you @FelixMau, but will change only collections dir in settings and remove it from `download_collections`, as this would lead to further errors in other functions which would also need path to collections and so on...
Instead, the preferred way to change the folder is by changing the related env `COLLECTION_DIR`.

**Comment by henhuy** [comment]
Added error message if collections or structure dir does not exists.
